# syntax=docker/dockerfile:1

FROM node:20-alpine

RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

ENV HOSTNAME=0.0.0.0
ENV PORT=3000

EXPOSE 3000

CMD ["yarn", "dev", "-H", "0.0.0.0", "-p", "3000"]
